import type { AnalyticsSnapshot } from '@/types/analytics';

/**
 * Mock analytics snapshots keyed by date-range label.
 * Each entry provides slightly different data to simulate filtering.
 */
export const analyticsFixtures: Record<string, AnalyticsSnapshot> = {
  '7d': {
    dateRange: { from: '2026-06-23', to: '2026-06-30' },
    kpi: {
      avgResponseTimeMinutes: 8.5,
      avgResponseTimeDelta: 12,
      userSatisfactionRate: 94,
      userSatisfactionDelta: 3,
      resolutionRate: 87,
      resolutionRateDelta: 5,
      activeHelpRequests: 42,
      activeHelpRequestsDelta: -8,
    },
    reportsTrends: [
      { date: 'Jun 24', reports: 42, resolved: 38 },
      { date: 'Jun 25', reports: 55, resolved: 50 },
      { date: 'Jun 26', reports: 48, resolved: 44 },
      { date: 'Jun 27', reports: 60, resolved: 55 },
      { date: 'Jun 28', reports: 65, resolved: 60 },
      { date: 'Jun 29', reports: 70, resolved: 65 },
      { date: 'Jun 30', reports: 78, resolved: 72 },
    ],
    helpRequestsByType: [
      { date: 'Jun 24', medical: 10, towing: 8, fuel: 5, repair: 7 },
      { date: 'Jun 26', medical: 12, towing: 10, fuel: 8, repair: 9 },
      { date: 'Jun 28', medical: 9, towing: 15, fuel: 11, repair: 13 },
      { date: 'Jun 30', medical: 14, towing: 18, fuel: 12, repair: 16 },
    ],
    userGrowth: [
      { month: 'Feb', users: 8500 },
      { month: 'Mar', users: 10200 },
      { month: 'Apr', users: 11500 },
      { month: 'May', users: 12800 },
      { month: 'Jun', users: 13228 },
    ],
    keyMetrics: {
      totalReportsThisMonth: 3247,
      totalReportsDelta: 15,
      helpRequestsCompleted: 1892,
      helpRequestsDelta: 22,
      newUsersThisMonth: 1228,
      newUsersDelta: 18,
    },
  },

  '30d': {
    dateRange: { from: '2026-06-01', to: '2026-06-30' },
    kpi: {
      avgResponseTimeMinutes: 9.2,
      avgResponseTimeDelta: 8,
      userSatisfactionRate: 91,
      userSatisfactionDelta: 1,
      resolutionRate: 83,
      resolutionRateDelta: 3,
      activeHelpRequests: 58,
      activeHelpRequestsDelta: 4,
    },
    reportsTrends: [
      { date: 'Jun 1', reports: 30, resolved: 25 },
      { date: 'Jun 7', reports: 45, resolved: 40 },
      { date: 'Jun 14', reports: 60, resolved: 52 },
      { date: 'Jun 21', reports: 72, resolved: 65 },
      { date: 'Jun 28', reports: 80, resolved: 74 },
    ],
    helpRequestsByType: [
      { date: 'Jun 1', medical: 18, towing: 14, fuel: 9, repair: 12 },
      { date: 'Jun 10', medical: 22, towing: 18, fuel: 14, repair: 16 },
      { date: 'Jun 20', medical: 20, towing: 24, fuel: 18, repair: 21 },
      { date: 'Jun 30', medical: 25, towing: 30, fuel: 20, repair: 28 },
    ],
    userGrowth: [
      { month: 'Jan', users: 7200 },
      { month: 'Feb', users: 8500 },
      { month: 'Mar', users: 10200 },
      { month: 'Apr', users: 11500 },
      { month: 'May', users: 12800 },
      { month: 'Jun', users: 13228 },
    ],
    keyMetrics: {
      totalReportsThisMonth: 9840,
      totalReportsDelta: 11,
      helpRequestsCompleted: 5612,
      helpRequestsDelta: 17,
      newUsersThisMonth: 3720,
      newUsersDelta: 14,
    },
  },

  '90d': {
    dateRange: { from: '2026-04-01', to: '2026-06-30' },
    kpi: {
      avgResponseTimeMinutes: 10.1,
      avgResponseTimeDelta: -5,
      userSatisfactionRate: 89,
      userSatisfactionDelta: -2,
      resolutionRate: 80,
      resolutionRateDelta: 1,
      activeHelpRequests: 71,
      activeHelpRequestsDelta: 10,
    },
    reportsTrends: [
      { date: 'Apr', reports: 280, resolved: 240 },
      { date: 'May', reports: 340, resolved: 300 },
      { date: 'Jun', reports: 410, resolved: 370 },
    ],
    helpRequestsByType: [
      { date: 'Apr', medical: 55, towing: 48, fuel: 30, repair: 42 },
      { date: 'May', medical: 68, towing: 60, fuel: 40, repair: 55 },
      { date: 'Jun', medical: 80, towing: 74, fuel: 52, repair: 68 },
    ],
    userGrowth: [
      { month: 'Jan', users: 7200 },
      { month: 'Feb', users: 8500 },
      { month: 'Mar', users: 10200 },
      { month: 'Apr', users: 11500 },
      { month: 'May', users: 12800 },
      { month: 'Jun', users: 13228 },
    ],
    keyMetrics: {
      totalReportsThisMonth: 29400,
      totalReportsDelta: 9,
      helpRequestsCompleted: 16200,
      helpRequestsDelta: 13,
      newUsersThisMonth: 10800,
      newUsersDelta: 10,
    },
  },

  'year': {
    dateRange: { from: '2026-01-01', to: '2026-12-31' },
    kpi: {
      avgResponseTimeMinutes: 11.4,
      avgResponseTimeDelta: -12,
      userSatisfactionRate: 86,
      userSatisfactionDelta: -5,
      resolutionRate: 76,
      resolutionRateDelta: -3,
      activeHelpRequests: 95,
      activeHelpRequestsDelta: 20,
    },
    reportsTrends: [
      { date: 'Jan', reports: 120, resolved: 95 },
      { date: 'Feb', reports: 145, resolved: 120 },
      { date: 'Mar', reports: 180, resolved: 155 },
      { date: 'Apr', reports: 220, resolved: 190 },
      { date: 'May', reports: 260, resolved: 230 },
      { date: 'Jun', reports: 310, resolved: 275 },
    ],
    helpRequestsByType: [
      { date: 'Jan', medical: 28, towing: 22, fuel: 14, repair: 19 },
      { date: 'Feb', medical: 34, towing: 28, fuel: 18, repair: 24 },
      { date: 'Mar', medical: 42, towing: 35, fuel: 24, repair: 30 },
      { date: 'Apr', medical: 50, towing: 42, fuel: 28, repair: 37 },
      { date: 'May', medical: 60, towing: 50, fuel: 34, repair: 44 },
      { date: 'Jun', medical: 72, towing: 60, fuel: 40, repair: 55 },
    ],
    userGrowth: [
      { month: 'Jan', users: 7200 },
      { month: 'Feb', users: 8500 },
      { month: 'Mar', users: 10200 },
      { month: 'Apr', users: 11500 },
      { month: 'May', users: 12800 },
      { month: 'Jun', users: 13228 },
    ],
    keyMetrics: {
      totalReportsThisMonth: 118000,
      totalReportsDelta: 6,
      helpRequestsCompleted: 64400,
      helpRequestsDelta: 9,
      newUsersThisMonth: 42800,
      newUsersDelta: 7,
    },
  },
};
