import type { DashboardOverview } from '@/types/dashboard';

export const dashboardFixtures: DashboardOverview = {
  metrics: [
    {
      id: 'totalUsers',
      label: 'Total Users',
      value: 12458,
      trend: {
        direction: 'up',
        percentage: 12,
        periodLabel: 'vs last month',
        meaning: 'positive',
      },
      targetRoute: '/users',
    },
    {
      id: 'totalReports',
      label: 'Total Reports',
      value: 3247,
      trend: {
        direction: 'down',
        percentage: 5,
        periodLabel: 'vs last month',
        meaning: 'negative',
      },
      targetRoute: '/reports',
    },
    {
      id: 'activeHelpRequests',
      label: 'Active Help Requests',
      value: 42,
      trend: {
        direction: 'up',
        percentage: 8,
        periodLabel: 'vs last month',
        meaning: 'positive',
      },
      targetRoute: '/help-requests',
    },
    {
      id: 'serviceProviders',
      label: 'Service Providers',
      value: 156,
      trend: {
        direction: 'up',
        percentage: 15,
        periodLabel: 'vs last month',
        meaning: 'positive',
      },
      targetRoute: '/providers',
    },
    {
      id: 'reportsToday',
      label: 'Reports Today',
      value: 87,
      trend: {
        direction: 'up',
        percentage: 22,
        periodLabel: 'vs yesterday',
        meaning: 'positive',
      },
      targetRoute: '/reports',
    },
    {
      id: 'urgentIncidents',
      label: 'Urgent Incidents',
      value: 12,
      trend: {
        direction: 'down',
        percentage: 18,
        periodLabel: 'vs last month',
        meaning: 'negative',
      },
      targetRoute: '/reports',
    },
  ],
  mapEvents: [
    {
      id: 'event-1',
      category: 'urgentReport',
      title: 'Urgent: Road closure on Main St',
      coordinates: { lat: 30.0388, lng: 31.2114 },
      status: 'pending',
      timestamp: '2026-06-15T10:30:00Z',
      targetRoute: '/reports',
    },
    {
      id: 'event-2',
      category: 'helpRequest',
      title: 'Help needed: Broken bridge',
      coordinates: { lat: 30.0585, lng: 31.3283 },
      status: 'in-progress',
      timestamp: '2026-06-15T09:15:00Z',
      targetRoute: '/help-requests',
    },
    {
      id: 'event-3',
      category: 'provider',
      title: 'New provider registered',
      coordinates: { lat: 30.0698, lng: 31.2477 },
      status: 'active',
      timestamp: '2026-06-15T08:00:00Z',
      targetRoute: '/providers',
    },
  ],
  activityEvents: [
    {
      id: 'activity-1',
      type: 'reportSubmitted',
      title: 'New report submitted: Road blocked',
      actorOrSource: 'user',
      timestamp: '2026-06-15T11:00:00Z',
      targetRoute: '/reports',
      tone: 'default',
    },
    {
      id: 'activity-2',
      type: 'reportVerified',
      title: 'Report verified: Bridge repaired',
      actorOrSource: 'admin',
      timestamp: '2026-06-15T10:30:00Z',
      targetRoute: '/reports',
      tone: 'success',
    },
    {
      id: 'activity-3',
      type: 'providerRegistered',
      title: 'Provider registered: City Services',
      actorOrSource: 'system',
      timestamp: '2026-06-15T09:45:00Z',
      targetRoute: '/providers',
      tone: 'info',
    },
    {
      id: 'activity-4',
      type: 'userFlagged',
      title: 'User flagged for inappropriate content',
      actorOrSource: 'moderator',
      timestamp: '2026-06-15T08:15:00Z',
      targetRoute: '/moderation',
      tone: 'warning',
    },
    {
      id: 'activity-5',
      type: 'announcementPublished',
      title: 'System maintenance scheduled',
      actorOrSource: 'system',
      timestamp: '2026-06-15T07:00:00Z',
      targetRoute: '/notifications',
      tone: 'info',
    },
  ],
  reportsTrend: [
    { label: 'Mon', value: 45, timestamp: '2026-06-09T00:00:00Z' },
    { label: 'Tue', value: 52, timestamp: '2026-06-10T00:00:00Z' },
    { label: 'Wed', value: 38, timestamp: '2026-06-11T00:00:00Z' },
    { label: 'Thu', value: 61, timestamp: '2026-06-12T00:00:00Z' },
    { label: 'Fri', value: 49, timestamp: '2026-06-13T00:00:00Z' },
    { label: 'Sat', value: 33, timestamp: '2026-06-14T00:00:00Z' },
    { label: 'Sun', value: 28, timestamp: '2026-06-15T00:00:00Z' },
  ],
  helpRequestCategories: [
    { category: 'Emergency', count: 18, targetRoute: '/help-requests?filter=emergency' },
    { category: 'Infrastructure', count: 12, targetRoute: '/help-requests?filter=infrastructure' },
    { category: 'Safety', count: 8, targetRoute: '/help-requests?filter=safety' },
    { category: 'Other', count: 4, targetRoute: '/help-requests?filter=other' },
  ],
  userDistribution: [
    { label: 'Admin', count: 5, percentage: 1.5, targetRoute: '/users?role=admin' },
    { label: 'Moderator', count: 23, percentage: 6.8, targetRoute: '/users?role=moderator' },
    { label: 'User', count: 287, percentage: 84.6, targetRoute: '/users?role=user' },
    { label: 'Guest', count: 28, percentage: 8.2, targetRoute: '/users?role=guest' },
  ],
  flaggedContent: [
    {
      id: 'flagged-1',
      title: 'Inappropriate report content',
      locationOrSource: 'Downtown Area',
      reason: 'Contains offensive language',
      reportedAgeLabel: '23 downvotes',
      status: 'pending',
      availableActions: ['approve', 'remove', 'flagUser'],
      targetRoute: '/moderation',
    },
    {
      id: 'flagged-2',
      title: 'Suspicious help request',
      locationOrSource: 'User: spammer@example.com',
      reason: 'Potential spam',
      reportedAgeLabel: '5 reports',
      status: 'pending',
      availableActions: ['approve', 'remove', 'flagUser'],
      targetRoute: '/moderation',
    },
    {
      id: 'flagged-3',
      title: 'Misleading provider info',
      locationOrSource: 'QuickFix Services',
      reason: 'Fake business listing',
      reportedAgeLabel: '12 flags',
      status: 'pending',
      availableActions: ['approve', 'remove', 'flagUser'],
      targetRoute: '/moderation',
    },
  ],
  flaggedContentPendingCount: 3,
  generatedAt: '2026-06-15T11:30:00Z',
};

export const emptyDashboardFixtures: DashboardOverview = {
  metrics: [],
  mapEvents: [],
  activityEvents: [],
  reportsTrend: [],
  helpRequestCategories: [],
  userDistribution: [],
  flaggedContent: [],
  flaggedContentPendingCount: 0,
  generatedAt: new Date().toISOString(),
};

export const errorDashboardFixtures: DashboardOverview = {
  metrics: [],
  mapEvents: [],
  activityEvents: [],
  reportsTrend: [],
  helpRequestCategories: [],
  userDistribution: [],
  flaggedContent: [],
  flaggedContentPendingCount: 0,
  generatedAt: new Date().toISOString(),
};
