import type { AdminNotification } from '@/types/notifications';

export const NOTIFICATIONS_FIXTURES: AdminNotification[] = [
  {
    id: 'notif-001',
    title: 'Road Closure Alert',
    message: 'Highway 5 is closed between exits 12–18 due to maintenance. Expect delays of up to 45 minutes.',
    status: 'Published',
    targetAudience: 'Broadcast',
    type: 'Maintenance',
    priority: 'High',
    roles: [],
    deliveryChannels: ['Push', 'InApp'],
    scheduledAt: null,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-002',
    title: 'Winter Storm Warning',
    message: 'Heavy snowfall expected tonight. Drive carefully and check your tire pressure.',
    status: 'Scheduled',
    targetAudience: 'SpecificRoles',
    type: 'Safety',
    priority: 'High',
    roles: ['Driver'],
    deliveryChannels: ['Push', 'InApp'],
    scheduledAt: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-003',
    title: 'New Towing Service Available',
    message: 'SpeedTow has joined the platform. Update your app to see their availability in your area.',
    status: 'Draft',
    targetAudience: 'Broadcast',
    type: 'Event',
    priority: 'Medium',
    roles: [],
    deliveryChannels: ['Push', 'InApp'],
    scheduledAt: null,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-004',
    title: 'Updated Terms of Service',
    message: 'Our Terms of Service have been updated. Please review the changes before your next login.',
    status: 'Failed',
    targetAudience: 'Broadcast',
    type: 'Legal',
    priority: 'High',
    roles: [],
    deliveryChannels: ['Push', 'InApp'],
    scheduledAt: null,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-005',
    title: 'System Maintenance Tonight',
    message: 'The platform will undergo scheduled maintenance from 02:00–04:00. Services may be unavailable.',
    status: 'Published',
    targetAudience: 'Broadcast',
    type: 'Maintenance',
    priority: 'Low',
    roles: [],
    deliveryChannels: ['Push', 'InApp'],
    scheduledAt: null,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-006',
    title: 'Driver Code of Conduct Policy Update',
    message: 'We have revised our Driver Code of Conduct. All drivers must acknowledge the new policy within 7 days.',
    status: 'Published',
    targetAudience: 'SpecificRoles',
    type: 'Policy',
    priority: 'Medium',
    roles: ['Driver'],
    deliveryChannels: ['Push', 'InApp'],
    scheduledAt: null,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
